[package]
name = "rust-vpn"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.155"
mio = {version = "1", features = ["os-poll", "os-ext", "net"]}
num-bigint = {version = "0.4", features = ["serde"]}
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0"